import rawBoroughs from "./data/zones.boroughs.json";
import type { SchedEntry, Zone } from "./types.js";

interface RawBoroughZone {
  id: string;
  name: string;
  kind: string;
  verified: boolean;
  src: string;
  checkedAt: string;
  sched: SchedEntry[];
  ratePence: number;
  maxStayHours: number;
  polys: number[][][];
}

/**
 * Borough-level CPZ fallback zones generated by data/etl.ts from real London
 * borough boundary GeoJSON. Regenerate with `npm run etl`.
 */
export const BOROUGH_ZONES: Zone[] = (rawBoroughs as RawBoroughZone[]).map((z) => ({
  id: z.id,
  name: z.name,
  kind: "borough",
  verified: z.verified,
  src: z.src,
  checkedAt: z.checkedAt,
  sched: z.sched,
  ratePence: z.ratePence,
  maxStayHours: z.maxStayHours,
  polys: z.polys.map((ring) => ring.map((p) => [p[0], p[1]] as [number, number])),
}));
